language: node_js
cache:
  directories:
    - node_modules

node_js:
  - '6.9.1'

branches:
  only:
    - master

before_install:
  - git config --global user.email "lotsabackscatter@gmail.com"
  - git config --global user.name "Travis CI"
script:
  - ng build

after_success:
  - ng github-pages:deploy --gh-token=$GH_TOKEN --gh-username="Travis CI"

after_script:
