language: node_js
cache:
  directories:
    - node_modules

node_js:
  - '6.9.1'

branches:
  only:
    - master

before_install:
  - git config --global user.email "lotsabackscatter@gmail.com"
  - git config --global user.name "Travis CI"

script:
  - ng github-pages:deploy
  
after_success:

after_script:
  - git remote set-url origin https://$GH_TOKEN@github.com/totaluniforms/totaluniforms.git
  - git fetch
  - git push origin gh-pages:gh-pages