language: node_js
cache:
  directories:
    - node_modules

node_js:
  - '6.9.1'

branches:
  only:
    - master

before_install:

script:
  - ng build

after_success:
  - ng github-pages:deploy --gh-token=GH_TOKEN --gh-username="Travis CI"

after_script:
