language: node_js
cache:
  directories:
    - node_modules

node_js:
  - '6.9.1'

branches:
  only:
    - master

before_install:

script:
  - ng build --prod

after_success:
  - ng ghpages --name="Travis CI" --email="lotsabackscatter@gmail.com" --repo=https://GH_TOKEN@github.com/totaluniforms/totaluniforms.git

after_script:
